"""
Sign-in detector module.

This module inspects Entra sign-in events and generates alerts for patterns
that may indicate suspicious login activity.

It currently detects:
- logins at unusual hours
- sign-ins from a new location
- multiple failed sign-ins followed by a success
"""

from config.settings import SUPPRESSED_USERS


def detect_signin_events(events):
    """
    Main sign-in detector entry point.

    The application calls this function with normalized sign-in events, and it
    returns all alerts generated by the sign-in detectors.
    """
    alerts = []

    alerts += detect_unusual_login_time(events)
    alerts += detect_new_location(events)
    alerts += detect_failed_then_success(events)

    return alerts


def detect_unusual_login_time(events):
    """Detect sign-ins that happen outside normal business hours."""
    alerts = []

    for event in events:
        user = event["user"]

        # Ignore users that are intentionally suppressed from alerting.
        if user in SUPPRESSED_USERS:
            continue

        hour = event.get("hour")

        # Treat logins before 1 AM or after 4:59M as unusual.
        if hour is not None and (1 <= hour <= 4):
            alerts.append({
                "severity": "medium",
                "type": "Unusual Login Time",
                "user": user,
                "detail": f"Login at hour {hour} UTC",
                "location": event.get("location", "Unknown"),
                "source": "Entra Sign-In Logs",
            })

    return alerts


def detect_new_location(events):
    """Detect sign-ins that are marked as coming from a new location."""
    alerts = []

    for event in events:
        user = event["user"]

        if user in SUPPRESSED_USERS:
            continue

        # The normalized sign-in event includes a boolean new_location flag.
        if event.get("new_location"):
            alerts.append({
                "severity": "low",
                "type": "New Location",
                "user": user,
                "detail": f"New location detected: {event.get('location', 'Unknown')}",
                "location": event.get("location", "Unknown"),
                "source": "Entra Sign-In Logs",
            })

    return alerts


def detect_failed_then_success(events):
    """Detect users who fail sign-in multiple times and then succeed."""
    alerts = []
    events_by_user = {}

    # Group events by user so we can analyze per-user sign-in sequences.
    for event in events:
        user = event["user"]

        if user in SUPPRESSED_USERS:
            continue

        events_by_user.setdefault(user, []).append(event)

    for user, user_events in events_by_user.items():
        # Sort the user's events chronologically using the created_datetime field.
        user_events.sort(key=lambda x: x.get("created_datetime", ""))

        failures_before_success = []

        for event in user_events:
            status = event.get("status")

            if status == "failure":
                failures_before_success.append(event)

            #Change to 3 later, but for now 1 just for testing.
            elif status == "success" and len(failures_before_success) >= 3:
                severity = "high" if event.get("new_location") else "medium"
                
                alerts.append({
                    "severity": severity,
                    "type": "Failed Sign-ins Followed by Success",
                    "user": user,
                    "detail": (
                        f"{len(failures_before_success)} failed sign-in(s) followed by success. "
                        f"Successful app: {event.get('app_display_name', 'Unknown')}. "
                        f"IP: {event.get('ip_address', 'Unknown')}. "
                        f"Last failure reason: {failures_before_success[-1].get('failure_reason', 'Unknown')}"
                    ),
                    "location": event.get("location", "Unknown"),
                    "source": "Entra Sign-In Logs",
                })

                # Reset the failure list after reporting an alert.
                failures_before_success = []

    return alerts