"""
Security Alert History

Stores generated medium/high/critical alerts in a readable JSON file.

This is separate from state.json and cache files.

state.json:
- Tracks processed Microsoft event IDs
- Prevents duplicate processing

security_alert_history.json:
- Tracks meaningful alerts generated by detectors
- Useful for review, tuning, and incident investigation
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from core.security_constants import ALERT_SEVERITIES

PROJECT_ROOT = Path(__file__).resolve().parents[2]
STATE_DIR = PROJECT_ROOT / "state"
ALERT_HISTORY_FILE = STATE_DIR / "security_alert_history.json"


def load_alert_history():
    """
    Load existing alert history from disk.
    """
    STATE_DIR.mkdir(exist_ok=True)

    if not ALERT_HISTORY_FILE.exists():
        return []

    try:
        with ALERT_HISTORY_FILE.open("r", encoding="utf-8") as file:
            content = file.read().strip()

            if not content:
                return []

            return json.loads(content)

    except json.JSONDecodeError:
        print("Warning: security alert history file was invalid. Resetting.")
        return []


def save_alert_history(history):
    """
    Save alert history to disk.
    """
    STATE_DIR.mkdir(exist_ok=True)

    with ALERT_HISTORY_FILE.open("w", encoding="utf-8") as file:
        json.dump(history, file, indent=2)


def build_alert_fingerprint(alert):
    """
    Build a stable fingerprint so identical alerts are not stored repeatedly.
    """
    return "|".join([
        str(alert.get("type", "")),
        str(alert.get("user", "")),
        str(alert.get("severity", "")),
        str(alert.get("source", "")),
        str(alert.get("detail", "")),
    ])


def add_alerts_to_history(existing_history, alerts, max_alerts=1000):
    """
    Add medium/high/critical alerts to alert history.

    Low/context alerts are intentionally excluded.
    """
    existing_fingerprints = {
        item.get("fingerprint")
        for item in existing_history
        if item.get("fingerprint")
    }

    updated_history = list(existing_history)

    for alert in alerts:
        severity = str(alert.get("severity", "")).lower()

        if severity not in ALERT_SEVERITIES:
            continue

        fingerprint = build_alert_fingerprint(alert)

        if fingerprint in existing_fingerprints:
            continue

        history_item = {
            "recorded_at": datetime.now(timezone.utc).isoformat(),
            "fingerprint": fingerprint,
            "severity": severity,
            "type": alert.get("type", "Unknown"),
            "user": alert.get("user", "Unknown"),
            "location": alert.get("location", "Unknown"),
            "source": alert.get("source", "Unknown"),
            "detail": alert.get("detail", ""),
        }

        updated_history.append(history_item)
        existing_fingerprints.add(fingerprint)

    return updated_history[-max_alerts:]